hyperparameters:
  Num_TCN: 10
  Num_Times: 3
  Num_Folds: 5
  Num_Epoch: 100
  Embedding_Dimension: 128
  LearningRate: 0.01
  MiniBatchSize: 16
  beta: 1
  WeightDecay: 0
  Dropout: 0

paths:
  LastStep_OutputFolderName: "/home/owkin/project/cytocommunity_results/unsupervised/graphs/"
  ThisStep_OutputFolderName: "/home/owkin/project/cytocommunity_results/unsupervised/"
